# Generated by Django 5.0.4 on 2024-04-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_progresslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='completed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='billed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
