# Generated by Django 5.0.4 on 2024-04-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_remove_challenge_start_challenge_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='billed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
