# Generated by Django 5.0.4 on 2024-04-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_remove_userprofile_address_alter_progresslog_billed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='steps_to_complete',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
