# Generated by Django 5.0.4 on 2024-04-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_userprofile_steps_to_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='current',
            field=models.IntegerField(default=0),
        ),
    ]
